# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/2.0/language-javascript/' | docs_url }} for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:14.16.0-browsers

jobs:
  build-core:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build Core
          command: npm run build:core

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy-core:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm run pub:core

workflows:
  version: 2
  deploy:
    jobs:
      - build-core
      - deploy-core:
          requires:
            - build-core
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
